spring.application.name=backend
# Enable the H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database connection settings
spring.datasource.url=jdbc:h2:mem:styora-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Tell JPA to use the H2 dialect and show generated SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true